let valorDias = 15;
let valorAsientos = 50;
let currentLang = 'es';

const translations = {
    'es': {
        'title': 'Revenue Management',
        'subtitle': 'Dynamic Pricing',
        'nav_dashboard': 'Dashboard',
        'nav_docs': 'Documentación',
        'export_btn': 'Exportar',
        'env_params': 'Parámetros del Entorno',
        'days_label': 'Días al despegue',
        'seats_label': 'Inventario',
        'inf_title': 'Recomendación del Modelo',
        'multiplier': 'Multiplicador de Precio',
        'discrete_action': 'Acción Discreta:',
        'heatmap_title': 'Mapa de Política: Random Forest',
        'leg_1_title': 'Acciones 0–2 (0.6x - 0.8x)',
        'leg_1_desc': 'Descuentos agresivos.',
        'leg_2_title': 'Acciones 3–5 (0.9x - 1.1x)',
        'leg_2_desc': 'Tarifa base neutra.',
        'leg_3_title': 'Acciones 6–8 (1.2x - 1.4x)',
        'leg_3_desc': 'Yield management alcista.',
        
        // Textos de Documentación
        'doc_title': 'Documentación del Proyecto',
        'doc_subtitle': 'Explicación de la metodología y parámetros del algoritmo.',
        'doc_sec1_title': '1. El Problema de Revenue Management',
        'doc_sec1_desc': 'El objetivo de esta herramienta es optimizar los ingresos de un tren de Alta Velocidad ajustando dinámicamente el precio del billete basándose en dos factores clave: los días restantes para la salida del tren y el número de asientos que aún quedan libres.',
        'doc_sec2_title': '2. Variables del Entorno',
        'doc_var1_name': 'Lead Time (Días):',
        'doc_var1_desc': 'Horizonte temporal. A menor tiempo, menor elasticidad del pasajero (dispuesto a pagar más).',
        'doc_var2_name': 'Inventario (Plazas):',
        'doc_var2_desc': 'La capacidad del tren. La escasez es el principal motor para aplicar políticas alcistas.',
        'doc_sec3_title': '3. El Algoritmo: Random Forest vs PPO',
        'doc_sec3_desc1': 'Durante el entrenamiento en el entorno Gym (Markov Decision Process), el agente de Deep Reinforcement Learning (PPO) sufrió un policy collapse, apostando únicamente por las tarifas más altas para evadir penalizaciones complejas.',
        'doc_sec3_desc2': 'Por tanto, la validación empírica mediante Monte Carlo demostró que la inteligencia generada mediante Random Forest Regressor lograba un uplift de ingresos superior (+17%), ofreciendo un mapa de calor equilibrado, lógico y económicamente viable. Esta interfaz expone dicha matriz optimizada.'
    },
    'en': {
        'title': 'Revenue Management',
        'subtitle': 'Dynamic Pricing',
        'nav_dashboard': 'Dashboard',
        'nav_docs': 'Documentation',
        'export_btn': 'Export',
        'env_params': 'Environment Parameters',
        'days_label': 'Lead Time (Days)',
        'seats_label': 'Inventory (Seats)',
        'inf_title': 'Model Recommendation',
        'multiplier': 'Price Multiplier',
        'discrete_action': 'Discrete Action:',
        'heatmap_title': 'Policy Map: Random Forest',
        'leg_1_title': 'Actions 0–2 (0.6x - 0.8x)',
        'leg_1_desc': 'Aggressive discounts.',
        'leg_2_title': 'Actions 3–5 (0.9x - 1.1x)',
        'leg_2_desc': 'Neutral base fare.',
        'leg_3_title': 'Actions 6–8 (1.2x - 1.4x)',
        'leg_3_desc': 'Bullish yield management.',
        
        // Documentation Texts
        'doc_title': 'Project Documentation',
        'doc_subtitle': 'Explanation of the methodology and algorithm parameters.',
        'doc_sec1_title': '1. The Revenue Management Problem',
        'doc_sec1_desc': 'The goal of this tool is to optimize the revenue of a High-Speed train by dynamically adjusting ticket prices based on two key factors: days remaining to departure and available seats.',
        'doc_sec2_title': '2. Environment Variables',
        'doc_var1_name': 'Lead Time (Days):',
        'doc_var1_desc': 'Time horizon. Closer to departure means lower passenger elasticity (willing to pay more).',
        'doc_var2_name': 'Inventory (Seats):',
        'doc_var2_desc': 'Train capacity. Scarcity is the main driver for bullish pricing policies.',
        'doc_sec3_title': '3. The Algorithm: Random Forest vs PPO',
        'doc_sec3_desc1': 'During training in the Gym environment, the Deep Reinforcement Learning (PPO) agent suffered a policy collapse, consistently outputting maximum fares to evade complex penalties.',
        'doc_sec3_desc2': 'Thus, Monte Carlo empirical validation demonstrated that the intelligence generated by the Random Forest Regressor achieved a superior revenue uplift (+17%), providing a balanced, logical, and economically viable heatmap. This interface exposes that optimized matrix.'
    }
};

// Función para cambiar de pestañas (Dashboard <-> Docs)
function switchTab(tabId) {
    const dashView = document.getElementById('view-dashboard');
    const docsView = document.getElementById('view-docs');
    const navDash = document.getElementById('nav-dashboard');
    const navDocs = document.getElementById('nav-docs');

    if(tabId === 'dashboard') {
        dashView.classList.remove('hidden');
        docsView.classList.add('hidden');
        navDash.className = "px-4 h-full tab-active transition-colors text-sm";
        navDocs.className = "px-4 h-full tab-inactive transition-colors text-sm";
        // Al volver al dashboard aseguramos que la gráfica se re-ajuste a su div
        setTimeout(renderizarGrafica, 50);
    } else {
        dashView.classList.add('hidden');
        docsView.classList.remove('hidden');
        navDash.className = "px-4 h-full tab-inactive transition-colors text-sm";
        navDocs.className = "px-4 h-full tab-active transition-colors text-sm";
    }
}

function setLang(lang) {
    currentLang = lang;
    const btnES = document.getElementById('btnES');
    const btnEN = document.getElementById('btnEN');
    if (btnES) btnES.className = lang === 'es' ? 'bg-white shadow-sm text-gray-900 px-3 py-1 rounded-md text-xs font-semibold transition-all' : 'text-gray-500 hover:text-gray-900 px-3 py-1 rounded-md text-xs font-semibold transition-colors';
    if (btnEN) btnEN.className = lang === 'en' ? 'bg-white shadow-sm text-gray-900 px-3 py-1 rounded-md text-xs font-semibold transition-all' : 'text-gray-500 hover:text-gray-900 px-3 py-1 rounded-md text-xs font-semibold transition-colors';
    
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
            el.innerText = translations[lang][key];
        }
    });

    ejecutarModeloIA();
}

function actualizarValores(d, a) {
    valorDias = parseInt(d);
    valorAsientos = parseInt(a);
    
    const sliderD = document.getElementById('sliderDias');
    const txtD = document.getElementById('txtDias');
    const sliderA = document.getElementById('sliderAsientos');
    const txtA = document.getElementById('txtAsientos');

    if (sliderD) sliderD.value = valorDias;
    if (txtD) txtD.innerText = valorDias + " d";
    if (sliderA) sliderA.value = valorAsientos;
    if (txtA) txtA.innerText = valorAsientos + " pl";

    ejecutarModeloIA();
    renderizarGrafica();
}

function obtenerAccionModelo(dias, asientos) {
    const clave = `${dias}_${asientos}`;
    if (typeof CEREBRO_IA !== 'undefined' && CEREBRO_IA[clave] !== undefined) {
        return CEREBRO_IA[clave];
    }
    return 4;
}

function ejecutarModeloIA() {
    const accion = obtenerAccionModelo(valorDias, valorAsientos);
    const multiplicadores = [0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4];
    const multi = multiplicadores[accion] !== undefined ? multiplicadores[accion] : 1.0;
    const pct = Math.round((multi - 1) * 100);

    const elMulti = document.getElementById('precioMultiplicador');
    const elAccion = document.getElementById('accionAgente');
    const elPct = document.getElementById('ajustePorcentaje');
    const elDesc = document.getElementById('textoExplicativoAccion');

    if (elMulti) elMulti.innerText = multi.toFixed(1) + "x";
    if (elAccion) elAccion.innerText = accion;
    
    if (elPct) {
        elPct.innerText = (pct > 0 ? "+" : "") + pct + "%";
        if (pct < 0) {
            elPct.className = "absolute top-4 right-4 text-xs font-bold text-fuchsia-700 bg-fuchsia-50 px-2 py-0.5 rounded-full border border-fuchsia-100";
        } else if (pct > 0) {
            elPct.className = "absolute top-4 right-4 text-xs font-bold text-orange-700 bg-orange-50 px-2 py-0.5 rounded-full border border-orange-100";
        } else {
            elPct.className = "absolute top-4 right-4 text-xs font-bold text-purple-700 bg-purple-100 px-2 py-0.5 rounded-full border border-purple-200";
        }
    }

    let desc = "";
    if (currentLang === 'es') {
        if (accion <= 2) desc = "Descuento estratégico activado por alta antelación y baja ocupación proyectada.";
        else if (accion <= 5) desc = "Tarifa base estable en zona de equilibrio del mercado.";
        else desc = "Recomendación de Yield Management alcista por alta demanda y escasez crítica de inventario.";
    } else {
        if (accion <= 2) desc = "Strategic discount recommended due to early lead time and low projected occupancy.";
        else if (accion <= 5) desc = "Stable base fare in market equilibrium zone.";
        else desc = "Bullish Yield Management recommended due to high demand and critical inventory scarcity.";
    }
    if (elDesc) elDesc.innerText = desc;
}

function descargarReporte() {
    const accion = obtenerAccionModelo(valorDias, valorAsientos);
    const multiplicadores = [0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4];
    const multi = multiplicadores[accion] || 1.0;
    const pct = Math.round((multi - 1) * 100);
    const fecha = new Date().toLocaleString();
    const descElem = document.getElementById('textoExplicativoAccion');
    const descText = descElem ? descElem.innerText : "";

    let contenido = `==================================================\n`;
    contenido += `      DYNAMIC PRICING OPTIMIZATION REPORT         \n`;
    contenido += `==================================================\n`;
    contenido += `Fecha / Date: ${fecha}\n`;
    contenido += `Modelo / Model: Random Forest Optimization\n\n`;
    contenido += `[ESTADO DEL INVENTARIO / INVENTORY STATUS]\n`;
    contenido += ` > Días (Lead Time): ${valorDias}\n`;
    contenido += ` > Plazas Libres (Seats): ${valorAsientos}\n\n`;
    contenido += `[DECISIÓN ALGORÍTMICA / ALGORITHMIC DECISION]\n`;
    contenido += ` > Acción Discreta (Action): ${accion}\n`;
    contenido += ` > Ajuste de Precio (Price Adj): ${multi.toFixed(1)}x (${pct > 0 ? "+" : ""}${pct}%)\n`;
    contenido += ` > Diagnóstico: ${descText}\n`;
    contenido += `==================================================\n`;

    const blob = new Blob([contenido], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Pricing_Report_${valorDias}d_${valorAsientos}s.txt`;
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}

function renderizarGrafica() {
    const contenedor = document.getElementById('graficaIA');
    // Si la pestaña actual no es dashboard, el contenedor estará oculto y Plotly fallará al medir.
    if (!contenedor || contenedor.offsetWidth === 0) return;

    let xDias = [];
    for (let i = 0; i <= 30; i++) xDias.push(i);
    let yAsientos = [];
    for (let i = 0; i <= 100; i++) yAsientos.push(i);
    
    let zAcciones = [];
    for (let a = 0; a <= 100; a++) {
        let fila = [];
        for (let d = 0; d <= 30; d++) {
            fila.push(obtenerAccionModelo(d, a));
        }
        zAcciones.push(fila);
    }

    // Escala de Colores Premium: Púrpura claro -> Violeta Intenso -> Naranja
    let heatmapColors = [
        [0, '#f3e8ff'],     // purple-100 (Descuento agresivo)
        [0.25, '#c084fc'],  // purple-400
        [0.5, '#7e22ce'],   // purple-700 (Neutro)
        [0.75, '#db2777'],  // pink-600
        [1, '#ea580c']      // orange-600 (Yield alcista máximo)
    ];

    let data = [
        {
            z: zAcciones, x: xDias, y: yAsientos, type: 'heatmap', zmin: 0, zmax: 8, colorscale: heatmapColors,
            colorbar: { thickness: 12, len: 0.8, tickfont: { family: 'Inter', size: 11, color: '#4b5563' } },
            hoverongaps: false
        },
        {
            x: [valorDias], y: [valorAsientos], mode: 'markers', type: 'scatter',
            marker: { color: '#ffffff', size: 14, symbol: 'circle', line: { color: '#581c87', width: 3 } },
            name: 'Punto de Inferencia'
        }
    ];

    Plotly.react('graficaIA', data, {
        autosize: true,
        margin: { t: 20, l: 50, r: 20, b: 40 },
        xaxis: { 
            title: { text: currentLang === 'es' ? 'Lead Time (Días)' : 'Lead Time (Days)', font: { family: 'Inter', size: 12, color: '#6b7280' } }, 
            tickfont: { family: 'Inter', color: '#6b7280' }, 
            gridcolor: '#f3f4f6' 
        },
        yaxis: { 
            title: { text: currentLang === 'es' ? 'Asientos Disponibles' : 'Available Seats', font: { family: 'Inter', size: 12, color: '#6b7280' } }, 
            tickfont: { family: 'Inter', color: '#6b7280' }, 
            gridcolor: '#f3f4f6' 
        },
        paper_bgcolor: 'rgba(0,0,0,0)', plot_bgcolor: 'rgba(0,0,0,0)',
        showlegend: false
    }, { responsive: true, displayModeBar: false });
}

window.onload = function() {
    const sliderD = document.getElementById('sliderDias');
    const sliderA = document.getElementById('sliderAsientos');
    
    if (sliderD) {
        sliderD.addEventListener('input', (e) => actualizarValores(e.target.value, valorAsientos));
    }
    if (sliderA) {
        sliderA.addEventListener('input', (e) => actualizarValores(valorDias, e.target.value));
    }
    
    setLang('es');
    actualizarValores(15, 50);
};